import bcrypt from 'bcryptjs';
const data = {
  users:[
    {  
      name: 'David',
      email: 'david@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {  
      name: 'jake',
      email: 'jake@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
  ],
    products: [
      {
        id: 1,  
        name: 'Free Shirt',
        slug: 'free-shirt',
        category: 'Shirts',
        image: '/images/shirt1.jpg',
        price: 67,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        id: 2,  
        name: 'Fit Shirt',
        slug: 'fit-shirt',
        category: 'Shirts',
        image: '/images/shirt2.jpg',
        price: 54,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        id: 3,  
        name: 'Slim Shirt',
        slug: 'slim-shirt',
        category: 'Shirts',
        image: '/images/shirt3.jpg',
        price: 34,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        id: 4,  
        name: 'Golf Pants',
        slug: 'golf-pants',
        category: 'Pants',
        image: '/images/pant1.jpg',
        price: 49,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        id: 5,  
        name: 'Fit Pants',
        slug: 'fit-pants',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 74,
        brand: 'Zara',
        description: 'A popular pants',
      },
      {
        id: 6,  
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 87,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };
  export default data